#!/bin/bash

export EGS_HOME=/media/gerhard/SeagateExpansionDrive/PhD/MC/EGSnrc18/EGS_XGI_extension/egs_xgi_home/
#if not using default:
export HEN_HOUSE=/home/gerhard/MC/EGSnrc18/HEN_HOUSE/
export EGS_CONFIG=/home/gerhard/MC/EGSnrc18/HEN_HOUSE/specs/gcc750
export my_machine=gcc750

n=500000000

cd ..
the_dir=./PW_Cylinder/
input0=2mmx1mmFOV_PlaneWave_Cylinder_G12d0p5_0
mv $the_dir"/"$input0".egsinp" .
../bin/$my_machine/Example_Usercode -p 521icru -i $input0 -r RefractiveIndexFile -n $n > $the_dir"/out_"$input0".txt"
mv $input0".egsinp" $the_dir

exit 0
