#! /bin/sh
#use version v6
export EGS_HOME=/media/gerhard/SeagateExpansionDrive/PhD/MC/EGSnrc18/EGS_XGI_extension/egs_xgi_home/
export HEN_HOUSE=/home/gerhard/MC/EGSnrc18/HEN_HOUSE/
export EGS_CONFIG=/home/gerhard/MC/EGSnrc18/HEN_HOUSE/specs/gcc750
export my_machine=gcc750

n=$1

#the_dir=./DoubleSlitExperiment/
#input0=DoubleSlit_d2em4_a2em5_CohPointSource_HO_5

the_dir=./LabSetup/
input0=LabSetup3

mv $the_dir"/"$input0".egsinp" .
#mkdir $input0
../bin/$my_machine/Example_Usercode -p 521icru -i $input0 -r RefractiveIndexFile -n $n  > "out_"$input0.txt #$the_dir"/out_"$input0".txt"
mv $input0".egsinp" $the_dir

exit 0
